
# Website settings
url: "https://controlledchaos.github.io"
is_user_page: true
is_project_page: false
remote_theme: theme-ccdzine
organization: "Controlled Chaos Design"
keywords: "website design, website development, website management, ClassicPress, ClassicPress themes, ClassicPress plugins, WordPress, WordPress themes, WordPress plugins, Advanced Custom Fields, Jekyll, Shopify, Liquid templates, HTML, HTML5, CSS, CSS3, SCSS, Sass, PHP, jQuery, SEO, Schema, SVG, image manipulation, Illustrator, Inkscape, PhotoShop, GIMP, Affinity, content writing, content management, fluent English, native English, United States"
owner: "Greg Sweet"
language: "en_US"
title: "Controlled Chaos Design"
description: "Custom website design and build. Free products to build your own."
author: "Controlled Chaos Design"
email: "gregsweet4@yahoo.com"
phone: "1-559-769-7600"
locality: "Exeter"
region: "California"
overlords: "USA"
postal: "93221"
favicon: "favicon.png"
site_icon: "site-icon.png"
site_image: "site-image.jpg"
site_thumb: "site-thumb.jpg"
timezone: "America/Los_Angeles"
markdown: kramdown
permalink: pretty

# General
body_class: "default-page"
page_type: "WebPage"
page_sidebar: true
footer_image: "bamboo.jpg"

# Collections
collections:
  front-page:
    directory: _front-page
    output: false
  front-slides:
    directory: _front-slides
    output: false
  modules:
    directory: _modules
    output: false
  projects:
    directory: _projects/content
    permalink: /projects/:title/
    layout: "project"
    output: true
    pagination:
      enabled: true
    paginate: 3
  snippets:
    directory: _snippets
    permalink: /snippets/:title/
    layout: "snippet"
    output: true

projects_path: "/projects/"

# Specific defaults
defaults:
  - scope:
      path: "" # empty string == all files in project.
      type: "posts"
    values:
      permalink: /posts/:title/
      layout: "post"
      author: "Greg Sweet"
      comments: true
      post_image: false # Fallback in templates.
      post_thumb: false # Fallback in templates.
      post_gallery: false # Heading to return true.
  - scope:
      path: "" # empty string == all files in project.
      type: "pages"
    values:
      layout: "page"
      page_image: false # Fallback in templates.
      page_thumb: false # Fallback in templates.

# Primary navigation entries
site_nav:
  - name: Services
    url: /services
  - name: Projects
    url: /projects
  - name: Downloads
    url: /downloads
  - name: Posts
    url: /posts
  - name: Snippets
    url: /snippets

# Blog pages
blog_view: preview # preview, grid, or full
blog_path: "/posts/"
paginate_path: "/posts/page:num/"
paginate: 9
category_path: /category/
category_layout: category_index.html
tag_page_layout: tags
tag_page_dir: tags
related_by: "tags or categories"

# Footer content
final_message: "CCDzine | No copyright. No synths!"

# Additional functionality
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-gist
  - jekyll-toc
  - jemoji
