
# Find more configuration in the `_data` directory.

# Website settings
url: "https://ccdzine.com"
is_user_page: true
is_project_page: false
remote_theme: theme-ccdzine
organization: "Controlled Chaos Design"
language: "en_US"
locale : "es_MX"
title: "Controlled Chaos Design"
description: "Custom website design and build. Free products to build your own."
author: "Controlled Chaos Design"
locality: "Exeter"
region: "California"
overlords: "USA"
postal: "93221"
favicon: "favicon.png"
site_icon: "site-icon.png"
site_image: "site-image.jpg"
site_thumb: "site-thumb.jpg"
timezone: "America/Los_Angeles"
markdown: kramdown
permalink: pretty

# General
body_class: "default-page"
page_type: "WebPage"
page_sidebar: true
footer_image: "bamboo.jpg"

# Collections
collections:
  category:
    directory: _category
    permalink: /:collection/:title
    output: true
    pagination:
      enabled: true
    paginate: 9
  tag:
    directory: _tag
    permalink: /:collection/:title
    output: true
    pagination:
      enabled: true
    paginate: 9
  front-page:
    directory: _front-page
    output: false
  front-slides:
    directory: _front-slides
    output: false
  widgets:
    directory: _widgets
    output: false
  projects:
    directory: _projects/content
    permalink: /:collection/:title/
    layout: "project"
    output: true
    pagination:
      enabled: true
    paginate: 3
  snippets:
    directory: _snippets
    permalink: /:collection/:title/
    layout: "snippet"
    output: true

# Specific defaults
defaults:
  - scope:
      path: "" # empty string == all files in project.
      type: "posts"
    values:
      permalink: /:collection/:title/
      layout: "post"
      page_type: "BlogPosting"
      author: "Greg Sweet"
      comments: true
      post_image: false # Fallback in templates.
      post_thumb: false # Fallback in templates.
      post_gallery: false # Heading to return true.
  - scope:
      path: "" # empty string == all files in project.
      type: "category"
    values:
      layout: "category"
      page_type: "CollectionPage"
      cover: "banner"
      page_image: false # Fallback in templates.
      page_thumb: false # Fallback in templates.
  - scope:
      path: "" # empty string == all files in project.
      type: "tag"
    values:
      layout: "tag"
      page_type: "CollectionPage"
      cover: "banner"
      page_image: false # Fallback in templates.
      page_thumb: false # Fallback in templates.
  - scope:
      path: "" # empty string == all files in project.
      type: "pages"
    values:
      layout: "default"
      page_type: "WebPage"
      cover: "banner"
      page_image: false # Fallback in templates.
      page_thumb: false # Fallback in templates.
  - scope:
      path: "" # empty string == all files in project.
      type: "projects"
    values:
      layout: "project"
      page_type: "WebPage"
      cover: "banner"
      page_image: false # Fallback in templates.
      page_thumb: false # Fallback in templates.

# Blog pages
blog_view: "list" # list, grid, or full
blog_path: "/posts/"
paginate_path: "/posts/page:num/"
paginate: 9
paged_style: "numeric" # numeric or standard
related_by: "tags or categories"

# Footer content
final_message: "CCDzine | No copyright. No synths!<br />* Sponsored by Chicos Bail Bonds."

# Additional functionality
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-gist
  - jekyll-toc
  - jemoji
